### ISSUE TITLE
検索画面

### ISSUE THREAD

**Issue by Nojio3** [Takahiko-Hiroshige/Mappi-Portfolio#21]
# 概要
- [ 検索画面の作成] 
# 目的
- [ 検索できるように] 
# タスク
- [ 検索画面を作成する]

**Comment by Takahiko-Hiroshige** [comment]
![image](https://user-images.githubusercontent.com/82690960/205434982-b15ce6e3-09e7-469f-bf63-b818bff715af.png)
react hooksのimport元は同じのため一行でまとめてください。


![image](https://user-images.githubusercontent.com/82690960/205434906-04341bc2-8dfc-42cd-b8c8-d0acabfeafca.png)
selectboxは共通コンポーネントで私が作成しているものがあるのでそちらを使用してください。
※使用方法はpages/p_select_box_sample.jsのコードを参考にしてください。


![image](https://user-images.githubusercontent.com/82690960/205435046-42cdac53-da08-477f-ab8f-a1847f72836a.png)
selectedを定義している理由は？
今回の実装だけだとselectedの値をそのまま使用すればよいかと。
過去に状態としてもっていた値を使用したい場合であっても基本的にstateで管理してください。
stateで管理していれば更新処理を行わない限りレンダリングされたとしても値は維持できます。
※値を維持する必要がなければ変数で持たせても問題はないです。
あとconstで定義させている値は基本的に更新不可になります。
※配列等であればpushを使用して要素の追加等はできますが。


![image](https://user-images.githubusercontent.com/82690960/205435616-a671dc27-1cc9-41b6-9b05-dbc9189b1e58.png)
itemChange関数の仮引数にeventを準備されていますが、呼出し側で引数にeventが実装されていません。

以上。
